### PR TITLE
Update to ember cli 0.2.7

### PR DESCRIPTION
**Pull request by mike-north**

### CODE REVIEW

**Comment by MaazAli** [comment]
We should probably also update Ember to v1.13.2.

**Comment by mike-north** [comment]
I'd reccomend developing this addon against the oldest version of ember you aim to support. With this PR, it will be tested against 1.10, 1.11, 1.12, 1.13 and 2.0

**Comment by mike-north** [comment]
@MaazAli please let me know if you need anything else in order to merge this in

**Comment by MaazAli** [comment]
This has been merged! Thanks.

**Pull request merged**
